series = extract_series_data(1298150)
    teams = extract_team_data(1298150)
    venues = extract_venue_data(1298150)
    matches = extract_match_data(1298150)

    insert_data(players1, "players")
    print("Done")
    insert_data(players2, "players")
    print("Done")
    insert_data(teams, "teams")
    print("Done")
    insert_data(series, "series")
    print("Done")
    insert_data(matches, "matches")
    print("Done")
    insert_data(venues, "venues")
    print("Done")